---
title: "Moose"
author: "Jessalyn Ayars"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(unmarked)
library(lme4)
library(here)
select <- dplyr::select
```


## Occupancy modeling

## Load data
```{r}
sitecovs <- read_csv(here("data-tidy", 'covs-site.csv'))
scale.smoke <- read.table(here("data-tidy", "covs-obs-smoke-scaled.csv")) %>%
  as.matrix()
scale.days <- read.table(here("data-tidy",'covs-obs-day-scaled.csv')) %>%
  as.matrix()
scale.temp <- read.table(here("data-tidy",'covs-obs-temp-scaled.csv')) %>%
  as.matrix()
moose_detections <- read.table(here("data-tidy", "dh-moose.csv"))
```

### Construct model frame
```{r}
moose.umf <- unmarkedFrameOccu(y = moose_detections, siteCovs = sitecovs, obsCovs = list(scale.days = scale.days, scale.smoke = scale.smoke, scale.temp = scale.temp))
```

### Occupancy model selection
```{r}
det.covs=c("scale.days", "I(scale.days^2)", "Road_Type", "scale.cheight", "I(scale.cheight^2)", "scale.dtr", "I(scale.dtr^2)", "scale.temp", "I(scale.temp^2)") 
occ.covs=c("conifer", "landmg2", "scale.elev", "I(scale.elev^2)", "scale.wadnr", "I(scale.wadnr^2)")

det.list=paste(det.covs, collapse="+")  
occ.list=paste(occ.covs, collapse="+")
form=as.formula(paste("~",det.list, "~", occ.list))   #this creates a formula that unmarked understands

moose.step <- occu(formula = form, moose.umf, method = "BFGS")

#first for detection covariates
while(max(summary(moose.step)[[2]][-1,4]) > 0.05){   
  det.remove=which(summary(moose.step)[[2]][,4] == max(summary(moose.step)[[2]][-1,4])) - 1  #not including the intercept, so -1
  if ((det.covs[det.remove] == "scale.days" & "I(scale.days^2)" %in% det.covs) |
      (det.covs[det.remove] == "scale.cheight" & "I(scale.cheight^2)" %in% det.covs) |
      (det.covs[det.remove] == "scale.dtr" & "I(scale.dtr^2)" %in% det.covs) |
      (det.covs[det.remove] == "scale.temp" & "I(scale.temp^2)" %in% det.covs)) {
    break
  }
  det.covs = det.covs[-det.remove]    
  det.list=paste(det.covs, collapse="+")
  form=as.formula(paste("~",det.list, "~", occ.list))
  moose.step <- occu(formula = form, moose.umf, method = "BFGS")
}
summary(moose.step) 

#now for occupancy 
while(max(summary(moose.step)[[1]][-1,4]) > 0.05){
  occ.remove=which(summary(moose.step)[[1]][,4] == max(summary(moose.step)[[1]][-1,4])) - 1  
  if ((occ.covs[occ.remove] == "scale.elev" & "I(scale.elev^2)" %in% occ.covs) |
      (occ.covs[occ.remove] == "scale.wadnr" & "I(scale.wadnr^2)" %in% occ.covs)) {
    break
  }  
  occ.covs = occ.covs[-occ.remove]
  occ.list=paste(occ.covs, collapse="+")
  form=as.formula(paste("~",det.list, "~", occ.list))
  moose.step <- occu(formula = form, moose.umf, method = "BFGS")
}
summary(moose.step) 

moose.smoke <- occu(~ Road_Type + scale.cheight + I(scale.cheight^2) + scale.dtr + 
    I(scale.dtr^2) + scale.smoke ~ scale.elev + I(scale.elev^2) + scale.wadnr, moose.umf, method = "BFGS")
summary(moose.smoke) # not significant
```

### Results tables
```{r}
# detection
moose.occ.det.final <- tibble(summary(moose.smoke)$det)
rows1 <- c("Intercept", "Road type (trail)", "Camera height", "Camera height^2", "Distance to linear feature", "Distance to linear feature^2", "PM 2.5")
moose.occ.det.final <- moose.occ.det.final %>% mutate(term = rows1) %>% relocate(term, .before=Estimate) %>%
  mutate(across(where(is.numeric), round, 3))
write_csv(moose.occ.det.final, here("results", "moose-occ-det.txt"))

# occupancy
moose.occ.occ.final <- tibble(summary(moose.smoke)$state)
rows1 <- c("Intercept", "Elevation", "Elevation^2", "Distance to road")
moose.occ.occ.final <- moose.occ.occ.final %>% mutate(term = rows1) %>% relocate(term, .before=Estimate) %>%
  mutate(across(where(is.numeric), round, 3))
write_csv(moose.occ.occ.final, here("results", "moose-occ-occ.txt"))
```


## Poisson regression

### data
```{r}
full_data.moose <- read_csv(here("data-tidy", "poisson-data-moose.csv"))
```

### Poisson model selection
```{r}
covs=c("scale.days", "I(scale.days^2)", "Road_Type", "scale.cheight", "I(scale.cheight^2)", "scale.dtr", "I(scale.dtr^2)", "scale.temp", "I(scale.temp^2)", "conifer", "landmg2", "scale.elev", "I(scale.elev^2)", "scale.wadnr", "I(scale.wadnr^2)")

covs.list = paste(covs, collapse="+")  
form = as.formula(paste("delta_times_pics ~ (1|Cell_ID) +",covs.list))

det.moose.step <- glmer(formula = form, full_data.moose, family = "poisson", glmerControl(optimizer = "bobyqa"))

while(max(summary(det.moose.step)$coefficients[-1,4]) > 0.05){
  remove=which(summary(det.moose.step)$coefficients[-1,4] == max(summary(det.moose.step)$coefficients[-1,4]))
  if ((covs[remove] == "scale.days" & "I(scale.days^2)" %in% covs) |
      (covs[remove] == "scale.cheight" & "I(scale.cheight^2)" %in% covs) |
      (covs[remove] == "scale.dtr" & "I(scale.dtr^2)" %in% covs) |
      (covs[remove] == "scale.temp" & "I(scale.temp^2)" %in% covs) |
      (covs[remove] == "scale.elev" & "I(scale.elev^2)" %in% covs) |
      (covs[remove] == "scale.wadnr" & "I(scale.wadnr^2)" %in% covs)) {
    break
  }  
  covs = covs[-remove]
  if(length(covs) > 0) {
    covs.list = paste(covs, collapse="+")
    form = as.formula(paste("delta_times_pics ~ (1|Cell_ID) +", covs.list))}
  else {
   form = as.formula("delta_times_pics ~ (1|Cell_ID)") 
  }
  det.moose.step <- glmer(formula = form, full_data.moose, family = "poisson", glmerControl(optimizer = "bobyqa"))
}
summary(det.moose.step) # add in base terms and check
det.moose.step.1 <- glmer(delta_times_pics ~ (1 | Cell_ID) + scale.days + I(scale.days^2) + 
    Road_Type + scale.cheight + I(scale.cheight^2) + scale.dtr + 
    I(scale.dtr^2) + scale.temp + I(scale.temp^2) + conifer + 
    landmg2 + scale.elev + I(scale.elev^2) + scale.wadnr, full_data.moose, family = "poisson", glmerControl(optimizer = "bobyqa"))
summary(det.moose.step.1) # drop land mg
det.moose.step.2 <- glmer(delta_times_pics ~ (1 | Cell_ID) + scale.days + I(scale.days^2) + 
    Road_Type + scale.cheight + I(scale.cheight^2) + scale.dtr + 
    I(scale.dtr^2) + scale.temp + I(scale.temp^2) + conifer + scale.elev + I(scale.elev^2) + scale.wadnr, full_data.moose, family = "poisson", glmerControl(optimizer = "bobyqa"))
summary(det.moose.step.2) # drop dtr^2
det.moose.step.3 <- glmer(delta_times_pics ~ (1 | Cell_ID) + scale.days + I(scale.days^2) + 
    Road_Type + scale.cheight + I(scale.cheight^2) + scale.dtr + scale.temp + I(scale.temp^2) + conifer + scale.elev + I(scale.elev^2) + scale.wadnr, full_data.moose, family = "poisson", glmerControl(optimizer = "bobyqa"))
summary(det.moose.step.3) # drop dtr
det.moose.step.4 <- glmer(delta_times_pics ~ (1 | Cell_ID) + scale.days + I(scale.days^2) + 
    Road_Type + scale.cheight + I(scale.cheight^2) + scale.temp + I(scale.temp^2) + conifer + scale.elev + I(scale.elev^2) + scale.wadnr, full_data.moose, family = "poisson", glmerControl(optimizer = "bobyqa"))
summary(det.moose.step.4) # drop days^2
det.moose.step.5 <- glmer(delta_times_pics ~ (1 | Cell_ID) + scale.days + 
    Road_Type + scale.cheight + I(scale.cheight^2) + scale.temp + I(scale.temp^2) + conifer + scale.elev + I(scale.elev^2) + scale.wadnr, full_data.moose, family = "poisson", glmerControl(optimizer = "bobyqa"))
summary(det.moose.step.5) # drop days
det.moose.step.6 <- glmer(delta_times_pics ~ (1 | Cell_ID) + Road_Type + scale.cheight + I(scale.cheight^2) + scale.temp + I(scale.temp^2) + conifer + scale.elev + I(scale.elev^2) + scale.wadnr, full_data.moose, family = "poisson", glmerControl(optimizer = "bobyqa"))
summary(det.moose.step.6) # drop temp^2
det.moose.step.7 <- glmer(delta_times_pics ~ (1 | Cell_ID) + Road_Type + scale.cheight + I(scale.cheight^2) + scale.temp + conifer + scale.elev + I(scale.elev^2) + scale.wadnr, full_data.moose, family = "poisson", glmerControl(optimizer = "bobyqa"))
summary(det.moose.step.7) # drop temp
det.moose.step.8 <- glmer(delta_times_pics ~ (1 | Cell_ID) + Road_Type + scale.cheight + I(scale.cheight^2) + conifer + scale.elev + I(scale.elev^2) + scale.wadnr, full_data.moose, family = "poisson", glmerControl(optimizer = "bobyqa"))
summary(det.moose.step.8) # drop conifer
det.moose.step.9 <- glmer(delta_times_pics ~ (1 | Cell_ID) + Road_Type + scale.cheight + I(scale.cheight^2) + scale.elev + I(scale.elev^2) + scale.wadnr, full_data.moose, family = "poisson", glmerControl(optimizer = "bobyqa"))
summary(det.moose.step.9) # drop cheight^2
det.moose.step.10 <- glmer(delta_times_pics ~ (1 | Cell_ID) + Road_Type + scale.cheight + scale.elev + I(scale.elev^2) + scale.wadnr, full_data.moose, family = "poisson", glmerControl(optimizer = "bobyqa"))
summary(det.moose.step.10)
det.moose.step.11 <- glmer(delta_times_pics ~ (1 | Cell_ID) + Road_Type + scale.elev + I(scale.elev^2) + scale.wadnr, full_data.moose, family = "poisson", glmerControl(optimizer = "bobyqa"))
summary(det.moose.step.11)

# adding pm 2.5
det.moose.smoke <-  glmer(delta_times_pics ~ (1 | Cell_ID) + Road_Type + scale.elev + I(scale.elev^2) + scale.wadnr + scale.smoke, data = full_data.moose, family = "poisson", glmerControl(optimizer = "bobyqa"))
summary(det.moose.smoke) # actually significant!
```

### results tables
```{r}
moose.det.final <- coef(summary(det.moose.smoke)) %>%
  as_tibble() 

rows1 <- c("Intercept", "Road type (trail)", "Elevation", "Elevation^2", "Distance to road", "PM 2.5")
moose.det.final <- moose.det.final %>% mutate(term = rows1) %>% relocate(term, .before=Estimate) %>%
  mutate(across(where(is.numeric), round, 3))

write_csv(moose.det.final, here("results", "moose-pois.txt"))
```

### Predictions for figure
-inspired by https://bbolker.github.io/mixedmodels-misc/glmmFAQ.html#lme4
```{r}
fm1 <- det.moose.smoke
summary(fm1)

newdat <- expand.grid(scale.smoke = seq(-1, 13, by=0.1), Road_Type = c("trail", "road"), scale.elev = 0, `I(scale.elev^2)` = 0, scale.wadnr = 0) 

newdat$delta_times_pics <- predict(fm1,newdat,re.form=NA) 
mm <- model.matrix(terms(fm1),newdat)


pvar1 <- diag(mm %*% tcrossprod(vcov(fm1),mm))
cmult <- 1.96 

newdat <- data.frame(
    newdat
    , plo = newdat$delta_times_pics-cmult*sqrt(pvar1)
    , phi = newdat$delta_times_pics+cmult*sqrt(pvar1)
) %>%
  mutate(smoke.cats = as.character(scale.smoke)) %>% 
  group_by(smoke.cats) %>%
  mutate(est = mean(delta_times_pics), lb = mean(plo), ub = mean(phi), Species = "Moose") %>%
  distinct(smoke.cats, .keep_all = T) %>%
  ungroup() %>%
  select(scale.smoke, lb, est, ub, Species)

ggplot(newdat, aes(y = est, x = scale.smoke)) + 
  geom_line(size = 1.5) + 
  geom_ribbon(aes(ymin = lb, ymax = ub), alpha = .3, linetype = 0) +
  theme_minimal() 

# write data
write_csv(newdat, here("results", "moose-pois-predictions.csv"))
```
