---
title: "White-tailed deer"
author: "Jessalyn Ayars"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(here)
library(lme4)
select <- dplyr::select
```

## Poisson regression 
```{r}
full_data.wtd <- read_csv(here("data-tidy", "poisson-data-wtd.csv"))
```

### Poisson model selection
```{r}
covs=c("scale.days", "I(scale.days^2)", "Road_Type", "scale.cheight", "I(scale.cheight^2)", "scale.dtr", "I(scale.dtr^2)", "scale.temp", "I(scale.temp^2)", "conifer", "landmg2", "scale.elev", "I(scale.elev^2)", "scale.wadnr", "I(scale.wadnr^2)")

covs.list = paste(covs, collapse="+")  
form = as.formula(paste("delta_times_pics ~ (1|Cell_ID) +",covs.list))

det.wtd.step <- glmer(formula = form, full_data.wtd, family = "poisson", glmerControl(optimizer = "bobyqa"))

while(max(summary(det.wtd.step)$coefficients[-1,4]) > 0.05){
  remove=which(summary(det.wtd.step)$coefficients[-1,4] == max(summary(det.wtd.step)$coefficients[-1,4]))
  if ((covs[remove] == "scale.days" & "I(scale.days^2)" %in% covs) |
      (covs[remove] == "scale.cheight" & "I(scale.cheight^2)" %in% covs) |
      (covs[remove] == "scale.dtr" & "I(scale.dtr^2)" %in% covs) |
      (covs[remove] == "scale.temp" & "I(scale.temp^2)" %in% covs) |
      (covs[remove] == "scale.elev" & "I(scale.elev^2)" %in% covs) |
      (covs[remove] == "scale.wadnr" & "I(scale.wadnr^2)" %in% covs)) {
    break
  }  
  covs = covs[-remove]
  if(length(covs) > 0) {
    covs.list = paste(covs, collapse="+")
    form = as.formula(paste("delta_times_pics ~ (1|Cell_ID) +", covs.list))}
  else {
   form = as.formula("delta_times_pics ~ (1|Cell_ID)") 
  }
  det.wtd.step <- glmer(formula = form, full_data.wtd, family = "poisson", glmerControl(optimizer = "bobyqa"))
} 
summary(det.wtd.step) # go from here: remove cheight^2
det.wtd.step.1 <- glmer(delta_times_pics ~ (1 | Cell_ID) + scale.days + I(scale.days^2) + 
    scale.cheight + scale.dtr + I(scale.dtr^2) + 
    scale.temp + I(scale.temp^2) + conifer + scale.elev + I(scale.elev^2) + 
    scale.wadnr + I(scale.wadnr^2), full_data.wtd, family = "poisson", glmerControl(optimizer = "bobyqa"))
summary(det.wtd.step.1) # remove cheight
det.wtd.step.2 <- glmer(delta_times_pics ~ (1 | Cell_ID) + scale.days + I(scale.days^2) + scale.dtr + I(scale.dtr^2) + 
    scale.temp + I(scale.temp^2) + conifer + scale.elev + I(scale.elev^2) + 
    scale.wadnr + I(scale.wadnr^2), full_data.wtd, family = "poisson", glmerControl(optimizer = "bobyqa"))
summary(det.wtd.step.2) # remove wadnr^2
det.wtd.step.3 <- glmer(delta_times_pics ~ (1 | Cell_ID) + scale.days + I(scale.days^2) + scale.dtr + I(scale.dtr^2) + 
    scale.temp + I(scale.temp^2) + conifer + scale.elev + I(scale.elev^2) + 
    scale.wadnr, full_data.wtd, family = "poisson", glmerControl(optimizer = "bobyqa"))
summary(det.wtd.step.3) # remove wadnr
det.wtd.step.4 <- glmer(delta_times_pics ~ (1 | Cell_ID) + scale.days + I(scale.days^2) + scale.dtr + I(scale.dtr^2) + 
    scale.temp + I(scale.temp^2) + conifer + scale.elev + I(scale.elev^2), full_data.wtd, family = "poisson", glmerControl(optimizer = "bobyqa"))
summary(det.wtd.step.4) # remove conifer
det.wtd.step.5 <- glmer(delta_times_pics ~ (1 | Cell_ID) + scale.days + I(scale.days^2) + scale.dtr + I(scale.dtr^2) + 
    scale.temp + I(scale.temp^2) + scale.elev + I(scale.elev^2), full_data.wtd, family = "poisson", glmerControl(optimizer = "bobyqa"))
summary(det.wtd.step.5) # remove days^2
det.wtd.step.6 <- glmer(delta_times_pics ~ (1 | Cell_ID) + scale.days + scale.dtr + I(scale.dtr^2) + 
    scale.temp + I(scale.temp^2) + scale.elev + I(scale.elev^2), full_data.wtd, family = "poisson", glmerControl(optimizer = "bobyqa"))
summary(det.wtd.step.6) # done!

det.wtd.smoke <- glmer(delta_times_pics ~ (1 | Cell_ID) + scale.days + scale.dtr + I(scale.dtr^2) + 
    scale.temp + I(scale.temp^2) + scale.elev + I(scale.elev^2) +scale.smoke, full_data.wtd, family = "poisson", glmerControl(optimizer = "bobyqa"))
summary(det.wtd.smoke) # not significant
```

### results tables
```{r}
wtd.det.final <- coef(summary(det.wtd.smoke)) %>%
  as_tibble() 

rows1 <- c("Intercept", "Days", "Distance to linear feature", "Distance to linear feature^2", "Temperature", "Temperature^2", "Elevation", "Elevation^2", "PM 2.5")
wtd.det.final <- wtd.det.final %>% mutate(term = rows1) %>% relocate(term, .before=Estimate) %>%
  mutate(across(where(is.numeric), round, 3))

write_csv(wtd.det.final, here("results", "wtd-pois.txt"))
```