---
title: "Cougar"
author: "Jessalyn Ayars"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(unmarked)
library(lme4)
library(here)
select <- dplyr::select
```


## Occupancy modeling

### Load data
```{r}
sitecovs <- read_csv(here("data-tidy", 'covs-site.csv'))
scale.smoke <- read.table(here("data-tidy", "covs-obs-smoke-scaled.csv")) %>%
  as.matrix()
scale.days <- read.table(here("data-tidy",'covs-obs-day-scaled.csv')) %>%
  as.matrix()
scale.temp <- read.table(here("data-tidy",'covs-obs-temp-scaled.csv')) %>%
  as.matrix()
cougar_detections <- read.table(here("data-tidy", "dh-cougar.csv"))
```

## Construct model frame
```{r}
cougar.umf <- unmarkedFrameOccu(y = cougar_detections, siteCovs = sitecovs, obsCovs = list(scale.days = scale.days, scale.smoke = scale.smoke, scale.temp = scale.temp))
```

### Occupancy model selection 
```{r}
det.covs=c("scale.days", "I(scale.days^2)", "Road_Type", "scale.cheight", "I(scale.cheight^2)", "scale.dtr", "I(scale.dtr^2)", "scale.temp", "I(scale.temp^2)") 
occ.covs=c("conifer", "landmg2", "scale.elev", "I(scale.elev^2)", "scale.wadnr", "I(scale.wadnr^2)")

det.list=paste(det.covs, collapse="+")  
occ.list=paste(occ.covs, collapse="+")
form=as.formula(paste("~",det.list, "~", occ.list))   #this creates a formula that unmarked understands

cougar.step <- occu(formula = form, cougar.umf, method = "L-BFGS-B")

#first for detection covariates
while(max(summary(cougar.step)[[2]][-1,4]) > 0.05){   
  det.remove=which(summary(cougar.step)[[2]][,4] == max(summary(cougar.step)[[2]][-1,4])) - 1  #not including the intercept, so -1
  if ((det.covs[det.remove] == "scale.days" & "I(scale.days^2)" %in% det.covs) |
      (det.covs[det.remove] == "scale.cheight" & "I(scale.cheight^2)" %in% det.covs) |
      (det.covs[det.remove] == "scale.dtr" & "I(scale.dtr^2)" %in% det.covs) |
      (det.covs[det.remove] == "scale.temp" & "I(scale.temp^2)" %in% det.covs)) {
    break
  }
  det.covs = det.covs[-det.remove]    
  det.list=paste(det.covs, collapse="+")
  form=as.formula(paste("~",det.list, "~", occ.list))
  cougar.step <- occu(formula = form, cougar.umf, method = "L-BFGS-B")
}
summary(cougar.step) # from here: remove temp^2
cougar.step.1 <- occu(~scale.days + Road_Type + scale.dtr + scale.temp ~ 
    conifer + landmg2 + scale.elev + I(scale.elev^2) + scale.wadnr + 
        I(scale.wadnr^2), cougar.umf, method = "L-BFGS-B")
summary(cougar.step.1) # remove days
cougar.step.2 <- occu(~ Road_Type + scale.dtr +scale.temp ~ 
    conifer + landmg2 + scale.elev + I(scale.elev^2) + scale.wadnr + 
        I(scale.wadnr^2), cougar.umf, method = "L-BFGS-B")
summary(cougar.step.2) # remove temp
cougar.step.3 <- occu(~ Road_Type + scale.dtr ~ 
    conifer + landmg2 + scale.elev + I(scale.elev^2) + scale.wadnr + 
        I(scale.wadnr^2), cougar.umf, method = "L-BFGS-B")
summary(cougar.step.3)
det.list <- "Road_Type+scale.dtr"

#now for occupancy 
while(max(summary(cougar.step.3)[[1]][-1,4]) > 0.05){
  occ.remove=which(summary(cougar.step.3)[[1]][,4] == max(summary(cougar.step.3)[[1]][-1,4])) - 1  
  if ((occ.covs[occ.remove] == "scale.elev" & "I(scale.elev^2)" %in% occ.covs) |
      (occ.covs[occ.remove] == "scale.wadnr" & "I(scale.wadnr^2)" %in% occ.covs)) {
    break
  }  
  occ.covs = occ.covs[-occ.remove]
  occ.list=paste(occ.covs, collapse="+")
  form=as.formula(paste("~",det.list, "~", occ.list))
  cougar.step.3 <- occu(formula = form, cougar.umf, method = "L-BFGS-B")
}
summary(cougar.step.3) 

cougar.smoke <- occu(~Road_Type + scale.dtr + scale.smoke ~ conifer, cougar.umf, method = "L-BFGS-B")
summary(cougar.smoke) # not significant
```


### Results tables
```{r}
# detection
cougar.occ.det.final <- tibble(summary(cougar.smoke)$det)
rows1 <- c("Intercept", "Road type (trail)", "Distance to linear feature", "PM 2.5")
cougar.occ.det.final <- cougar.occ.det.final %>% mutate(term = rows1) %>% relocate(term, .before=Estimate) %>%
  mutate(across(where(is.numeric), round, 3))
write_csv(cougar.occ.det.final, here("results", "cougar-occ-det.txt"))

# occupancy
cougar.occ.occ.final <- tibble(summary(cougar.smoke)$state)
rows1 <- c("Intercept", "Habitat type (other)")
cougar.occ.occ.final <- cougar.occ.occ.final %>% mutate(term = rows1) %>% relocate(term, .before=Estimate) %>%
  mutate(across(where(is.numeric), round, 3))
write_csv(cougar.occ.occ.final, here("results", "cougar-occ-occ.txt"))
```

## Poisson regression

### Load data
```{r}
full_data.cougar <- read_csv(here("data-tidy", "poisson-data-cougar.csv"))
```

### Poisson model selection
```{r}
covs=c("scale.days", "I(scale.days^2)", "Road_Type", "scale.cheight", "I(scale.cheight^2)", "scale.dtr", "I(scale.dtr^2)", "scale.temp", "I(scale.temp^2)", "conifer", "landmg2", "scale.elev", "I(scale.elev^2)", "scale.wadnr", "I(scale.wadnr^2)")

covs.list = paste(covs, collapse="+")  
form = as.formula(paste("delta_times_pics ~ (1|Cell_ID) +",covs.list))

det.cougar.step <- glmer(formula = form, full_data.cougar, family = "poisson", glmerControl(optimizer = "bobyqa"))

while(max(summary(det.cougar.step)$coefficients[-1,4]) > 0.05){
  remove=which(summary(det.cougar.step)$coefficients[-1,4] == max(summary(det.cougar.step)$coefficients[-1,4]))
  if ((covs[remove] == "scale.days" & "I(scale.days^2)" %in% covs) |
      (covs[remove] == "scale.cheight" & "I(scale.cheight^2)" %in% covs) |
      (covs[remove] == "scale.dtr" & "I(scale.dtr^2)" %in% covs) |
      (covs[remove] == "scale.temp" & "I(scale.temp^2)" %in% covs) |
      (covs[remove] == "scale.elev" & "I(scale.elev^2)" %in% covs) |
      (covs[remove] == "scale.wadnr" & "I(scale.wadnr^2)" %in% covs)) {
    break
  }  
  covs = covs[-remove]
  if(length(covs) > 0) {
    covs.list = paste(covs, collapse="+")
    form = as.formula(paste("delta_times_pics ~ (1|Cell_ID) +", covs.list))}
  else {
   form = as.formula("delta_times_pics ~ (1|Cell_ID)") 
  }
  det.cougar.step <- glmer(formula = form, full_data.cougar, family = "poisson", glmerControl(optimizer = "bobyqa"))
}
summary(det.cougar.step) # from here, drop land mg
det.cougar.1 <- glmer(delta_times_pics ~ (1 | Cell_ID) + scale.days + I(scale.days^2) + 
    Road_Type + scale.cheight + I(scale.cheight^2) + scale.dtr + 
    I(scale.dtr^2) + scale.temp + I(scale.temp^2) + conifer + scale.elev + I(scale.elev^2) + scale.wadnr + I(scale.wadnr^2), full_data.cougar, family = "poisson", glmerControl(optimizer = "bobyqa"))
summary(det.cougar.1) # drop days^2
det.cougar.2 <- glmer(delta_times_pics ~ (1 | Cell_ID) + scale.days + 
    Road_Type + scale.cheight + I(scale.cheight^2) + scale.dtr + 
    I(scale.dtr^2) + scale.temp + I(scale.temp^2) + conifer + scale.elev + I(scale.elev^2) + scale.wadnr + I(scale.wadnr^2), full_data.cougar, family = "poisson", glmerControl(optimizer = "bobyqa"))
summary(det.cougar.2) # drop wadnr
det.cougar.3 <- glmer(delta_times_pics ~ (1 | Cell_ID) + scale.days + 
    Road_Type + scale.cheight + I(scale.cheight^2) + scale.dtr + 
    I(scale.dtr^2) + scale.temp + I(scale.temp^2) + conifer + scale.elev + I(scale.elev^2) + scale.wadnr, full_data.cougar, family = "poisson", glmerControl(optimizer = "bobyqa"))
summary(det.cougar.3) # drop cheight^2
det.cougar.4 <- glmer(delta_times_pics ~ (1 | Cell_ID) + scale.days + 
    Road_Type + scale.cheight + scale.dtr + I(scale.dtr^2) + scale.temp + I(scale.temp^2) + conifer + scale.elev + I(scale.elev^2) + scale.wadnr, full_data.cougar, family = "poisson", glmerControl(optimizer = "bobyqa"))
summary(det.cougar.4) # drop cheight
det.cougar.5 <- glmer(delta_times_pics ~ (1 | Cell_ID) + scale.days + 
    Road_Type + scale.dtr + I(scale.dtr^2) + scale.temp + I(scale.temp^2) + conifer + scale.elev + I(scale.elev^2) + scale.wadnr, full_data.cougar, family = "poisson", glmerControl(optimizer = "bobyqa"))
summary(det.cougar.5) # drop temp^2
det.cougar.6 <- glmer(delta_times_pics ~ (1 | Cell_ID) + scale.days + 
    Road_Type + scale.dtr + I(scale.dtr^2) + scale.temp + conifer + scale.elev + I(scale.elev^2) + scale.wadnr, full_data.cougar, family = "poisson", glmerControl(optimizer = "bobyqa"))
summary(det.cougar.6) # drop wadnr
det.cougar.7 <- glmer(delta_times_pics ~ (1 | Cell_ID) + scale.days + 
    Road_Type + scale.dtr + I(scale.dtr^2) + scale.temp + conifer + scale.elev + I(scale.elev^2), full_data.cougar, family = "poisson", glmerControl(optimizer = "bobyqa"))
summary(det.cougar.7)
det.cougar.8 <- glmer(delta_times_pics ~ (1 | Cell_ID) + scale.days + 
    Road_Type + scale.dtr + I(scale.dtr^2) + scale.temp + conifer + scale.elev, full_data.cougar, family = "poisson", glmerControl(optimizer = "bobyqa"))
summary(det.cougar.8) # drop dtr^2
det.cougar.9 <- glmer(delta_times_pics ~ (1 | Cell_ID) + scale.days + 
    Road_Type + scale.dtr + scale.temp + conifer + scale.elev, full_data.cougar, family = "poisson", glmerControl(optimizer = "bobyqa"))
summary(det.cougar.9) # drop days
det.cougar.10 <- glmer(delta_times_pics ~ (1 | Cell_ID) + 
    Road_Type + scale.dtr + scale.temp + conifer + scale.elev, full_data.cougar, family = "poisson", glmerControl(optimizer = "bobyqa"))
summary(det.cougar.10) # drop temp
det.cougar.11 <- glmer(delta_times_pics ~ (1 | Cell_ID) + 
    Road_Type + scale.dtr + conifer + scale.elev, full_data.cougar, family = "poisson", glmerControl(optimizer = "bobyqa"))
summary(det.cougar.11) # drop elev
det.cougar.12 <- glmer(delta_times_pics ~ (1 | Cell_ID) + 
    Road_Type + scale.dtr + conifer, full_data.cougar, family = "poisson", glmerControl(optimizer = "bobyqa"))
summary(det.cougar.12) # drop dtr
det.cougar.13 <- glmer(delta_times_pics ~ (1 | Cell_ID) + 
    Road_Type + conifer, full_data.cougar, family = "poisson", glmerControl(optimizer = "bobyqa"))
summary(det.cougar.13)

# adding pm 2.5
det.cougar.smoke <-  glmer(delta_times_pics ~ (1 | Cell_ID) + Road_Type + conifer + scale.smoke, data = full_data.cougar, family = "poisson", glmerControl(optimizer = "bobyqa"))
summary(det.cougar.smoke) # not significant
```

### results tables
```{r}
cougar.det.final <- coef(summary(det.cougar.smoke)) %>%
  as_tibble() 

rows1 <- c("Intercept", "Road type (trail)", "Habitat type (other)", "PM 2.5")
cougar.det.final <- cougar.det.final %>% mutate(term = rows1) %>% relocate(term, .before=Estimate) %>%
  mutate(across(where(is.numeric), round, 3))

write_csv(cougar.det.final, here("results", "cougar-pois.txt"))
```
